Program([ "test.cpp",
          "backward_pde_pricer.cpp",
          "bootstrapped_local_vol.cpp",
          "bs_pricer.cpp",
          "calibration_constraint.cpp",
          "dividend_policy.cpp",
          "forward_pde_pricer.cpp",
          "interpolation_builder.cpp",
          "interpolation_builder_2d.cpp",
          "option.cpp",
          "payoff.cpp",
          "pricer.cpp",
          "real_2d_function.cpp",
          "real_function.cpp",
          "round_trip.cpp",
          "util.cpp" ],
        CCFLAGS="/EHsc /O2 /IEigen",
        MSVC_VERSION=15.0)